# Generated by Django 5.1.4 on 2025-01-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
    ]
