# Generated by Django 5.1.4 on 2025-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('commodities', 'Commodities'), ('electronics', 'Electronics'), ('apparels', 'Apparels'), ('vehicles', 'Vehicles'), ('property', 'Property'), ('art', 'Art'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
