# Generated by Django 5.1.4 on 2025-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://cdn2.iconfinder.com/data/icons/creative-icons-2/64/PACKAGING_DESIGN-1024.png', upload_to='product_images/'),
        ),
    ]
