# Generated by Django 5.1.4 on 2025-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_bid_options_remove_bid_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
