# Generated by Django 5.1.4 on 2025-01-29 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_bid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='id',
            new_name='bid_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.product'),
            preserve_default=False,
        ),
    ]
